### PR TITLE
Update Travis to LTS SDK version

### PR DESCRIPTION
**Pull request by dchristensen**

### CODE REVIEW

**Comment by staviloglu** [comment]
thx @dchristensen

**Comment by dchristensen** [comment]
@staviloglu any chance you could push an updated Nuget package?

**Comment by staviloglu** [comment]
Hi, @dchristensen 
The packages you find on nuget are the latest ones, do you have any problem?
https://www.nuget.org/packages/Taviloglu.Wrike.ApiClient/2.1.1
https://www.nuget.org/packages/Taviloglu.Wrike.Core/2.1.3
https://www.nuget.org/packages/Taviloglu.Wrike.WebHook/2.0.0
https://www.nuget.org/packages/Taviloglu.Wrike.ApiClient.Extensions/2.0.0

**Comment by dchristensen** [comment]
Ahh, no I see they're up to date now..

I just think my project wasn't getting the latest Core package because I'm just referencing the ApiClient package which has a dependency on Core@2.1.2.  I'll just reference Core@2.1.3 explicitly and it should be good.

Thanks!

**Pull request merged**
